ALTER TYPE "CommercialOrderStatus" ADD VALUE 'FULFILLING';
ALTER TYPE "CommercialOrderStatus" ADD VALUE 'FULFILLED';
ALTER TYPE "CommercialOrderStatus" ADD VALUE 'PAYMENT_FAILED';
ALTER TYPE "CommercialOrderStatus" ADD VALUE 'REFUNDED';
ALTER TYPE "CommercialOrderStatus" ADD VALUE 'PARTIALLY_REFUNDED';

ALTER TYPE "PaymentStatus" ADD VALUE 'PROCESSING';
ALTER TYPE "PaymentStatus" ADD VALUE 'CANCELED';
ALTER TYPE "PaymentStatus" ADD VALUE 'REQUIRES_REVIEW';
