/**
 * LaunchOS 产品语言规范
 *
 * 普通用户默认看到中文，并且不需要理解底层技术。
 * 默认隐藏：Docker、SSH、Artifact、Container、Runtime、framework。
 * 「上线」代替「部署」；「应用」是用户主对象；技术细节只放在高级模式。
 */
export const PRODUCT_COPY = {
  goLive: '上线',
  goingLive: '上线中…',
  goLiveAgain: '重新上线',
  liveSuccess: '上线成功',
  visitApp: '访问应用',
  appStatus: '应用状态',
  visitUrl: '访问地址',
  copyVisitUrl: '复制',
  copiedVisitUrl: '已复制',
  visitUrlPreparing: '访问地址准备中',
  visitUrlPreparingHint: '系统正在准备访问地址，无需你操作。',
  accessEntryPending: '应用已运行，正在等待访问入口配置',
  accessEntryPendingHint: '服务已在托管服务器上安全运行，访问入口将在后续配置（域名 / 网关）。',
  visitUrlReadyStatus: '可以访问',
  visitUrlPreparingStatus: '准备中',
  codeSource: '代码来源',
  codeSourceHint: '你的程序代码存放的位置。',
  codeVersion: '代码版本',
  codeVersionHint: '代码的不同版本线路，一般不用修改。',
  codeVersionAuto: '自动检测',
  codeVersionKeepDefault: '如果你不知道代码版本是什么，请保持默认设置。',
  codeVersionWhat: '什么是代码版本？',
  codeVersionExplain:
    '代码仓库通常有不同版本线路。\nLaunchOS 会自动选择推荐版本。\n如果你不知道，请保持默认。',
  programType: '程序类型',
  programTypeHint: '系统自动识别你的程序技术类型。',
  programTypeAuto: '自动识别',
  runtimeEnv: '运行环境',
  runtimeEnvHint: '应用运行需要的软件环境。',
  runConfig: '运行配置',
  launchHistory: '上线记录',
  appInfo: '应用信息',
  techDetails: '查看技术详情',
  hideTechDetails: '收起技术详情',
  advanced: '高级设置',
  detectProject: '检测应用',
  detecting: '检测中…',
  detectSuccess: '检测成功',
  defaultReady: '默认设置即可上线。',
  githubProject: 'GitHub 代码',
  uploadCode: '上传代码文件',
  aiProject: 'AI 生成应用',
  demoProject: '示例应用',
  port: '端口',
  buildCommand: '构建命令',
  demoBadge: '体验应用',
  analyzingTitle: '正在检测你的应用',
  analyzingProgress: '正在分析你的应用...',
  analyzingDone: '检测完成',
  analyzingSubtitle: 'LaunchOS 已准备好上线配置。',
  analyzingReadingCode: '正在读取代码',
  analyzingDetectTech: '正在识别技术类型',
  analyzingConfirmStart: '正在确认启动方式',
  analyzingPrepareConfig: '正在准备上线配置',
  yourProject: '你的应用',
  autoConfig: '自动配置',
  installDeps: '安装依赖',
  installDepsHint: '上线前会自动安装应用依赖。',
  buildMethod: '构建方式',
  buildMethodNone: '无需额外构建',
  startMethod: '启动方式',
  unsupportedProject: '暂时无法自动识别这个应用',
  unsupportedProjectHint: '你仍可以查看高级检测结果，或稍后补充支持。',
  unsupportedCannotLaunch: '当前版本暂不支持自动上线这种技术类型。',
  goLiveLater: '稍后上线',
  detectCode: '检测代码',
  detectingCode: '正在检测代码…',
  detectCodeSuccess: '✓ 已找到代码仓库',
  detectCodeVersionSuccess: '✓ 默认代码版本',
  detectCodeFailed: '无法读取代码仓库',
  detectCodePrivate: '这个代码仓库需要授权才能访问。',
  detectCodePrivateHint: '当前更适合公共仓库。私有仓库需授权后才能读取。',
  connectGithubLater: '连接 GitHub',
  codeVersionAutoHint: '通常保持自动即可。',
  codeVersionDetectFailed: '暂时无法自动检测代码版本',
  stepAppInfo: '应用信息',
  stepConnectCode: '连接代码',
  stepSmartDetect: '智能检测',
  nextConnectCode: '下一步：连接代码',
  continueNext: '继续',
  purposeUnset: '未设置用途',
  editPurpose: '编辑',
  savePurpose: '保存用途',
  purposeSaved: '用途已更新',
  demoAnalysisSkip: '示例应用使用内置演示代码，无需读取远程仓库。',
  bindCode: '连接代码',
  createApp: '创建应用',
  appNotFound: '应用不存在',
  createAppFailed: '创建应用失败',
  createAppSuccess: '应用创建成功',
  noAppsYet: '还没有应用。',
  appName: '应用名称',
  appDetail: '应用详情',
  githubUrl: '代码仓库地址',
  githubUrlHint: '填写 GitHub / GitLab 地址。',
  githubUrlRequired: '请填写代码仓库地址',
  githubUrlDetectHint: '输入仓库地址后，LaunchOS 会自动检测默认代码版本。',
  aiComingSoon: 'AI 生成应用即将开放。现在可以用 GitHub 代码或示例应用完成第一次上线。',
  aiComingSoonHint: '稍后会支持。现在可以先用 GitHub 或示例应用。',
  demoChoiceHint: '用现成的体验应用走一遍上线。',
  backToApps: '← 我的应用',
  appsListTitle: '应用列表',
  viewApps: '查看我的应用',
  appsCount: '应用数量',
  goLiveFailed: '应用上线失败',
  appDeleted: '应用已删除',
  smartAdvice: '智能建议',
  chooseHosting: '选择上线方式',
  chooseHostingHint: '先决定应用放在哪里运行，确认后再开始上线。',
  hostingLaunchos: 'LaunchOS 自动托管',
  hostingLaunchosHint: '不用准备服务器，LaunchOS 帮你运行应用。',
  hostingMyServer: '我的服务器',
  hostingMyServerHint: '把应用放到你已经添加的服务器上。',
  hostingLocation: '运行位置',
  confirmGoLive: '确认上线',
  selectServer: '选择服务器',
  noServersYet: '还没有服务器。添加一台后即可在上面运行应用。',
  addServer: '添加服务器',
  addServerHint: '填写名称、地址和登录信息即可。',
  serverReady: '可以运行应用',
  serverNotReady: '还不能运行应用',
  serverUnknown: '尚未确认',
  checkServer: '检查是否可用',
  checkingServer: '检查中…',
  serverUsable: '这台服务器可以运行应用。',
  serverUnusable: '这台服务器暂时不能运行应用，请换一台或重新添加。',
  startApp: '启动',
  stopApp: '停止',
  restartApp: '重启',
  startingApp: '启动中…',
  stoppingApp: '停止中…',
  restartingApp: '重启中…',
  runtimeLogs: '运行日志',
  refreshLogs: '刷新日志',
  noLogsYet: '还没有运行日志。',
  manageApp: '管理应用',
  appsHint: '像管理手机应用一样，随时查看状态、启动、停止或重启。',
  goLiveFirst: '完成一次上线后，就可以在这里管理应用。',
  openApp: '打开应用',
  foundNewVersion: '发现新版本',
  confirmGoLiveAgain: '确认上线新版本',
  versionHistory: '上线版本',
  issuesCenter: '问题中心',
  copyToAssistant: '复制给开发助手',
  noIssues: '还没有发现问题。',
  noProblems: '✓ 暂未发现问题',
  problemsAndAdvice: '问题与建议',
  viewAllVersions: '查看全部版本',
  viewLaunchHistory: '查看上线记录',
  recentLaunch: '最近上线',
  backToApp: '← 返回应用',
  allVersionsTitle: '全部版本',
  loadLaunchHistoryFailed: '暂时无法加载上线记录，请稍后重试。',
  loadVersionsFailed: '暂时无法加载版本列表，请稍后重试。',
  currentlyRunning: '当前运行',
  liveSuccessShort: '上线成功',
  noLaunchHistory: '还没有上线记录',
  secureAccessEnabled: '✓ 安全访问已启用',
  goLiveNow: '立即上线',
  notLiveYet: '你的应用还没有上线',
  connectCodeFirst: '请先连接代码来源',
  analyzingApp: '正在检测应用…',
  launchFailedBanner: '上线失败',
  viewCause: '查看原因',
  moreActions: '更多',
  healthOk: '正常',
  healthBad: '访问异常',
  healthUnknown: '等待检测',
  lastCheckedJustNow: '刚刚',
  lastCheckedMinutes: '分钟前',
  techType: '技术类型',
  lastSynced: '最近同步',
  currentBranch: '当前代码版本',
  rollback: '恢复此版本',
  rollingBack: '正在恢复…',
  currentVersion: '当前运行版本',
  restoreConfirmTitle: '确定恢复到 {version} 吗？',
  restoreConfirmHint1: '公网地址保持不变',
  restoreConfirmHint2: '当前版本不会立即删除',
  restoreConfirmHint3: '如果恢复失败，当前线上版本会继续运行',
  restoreConfirmCancel: '取消',
  restoreConfirmOk: '确认恢复',
  restoreSuccessTitle: '版本恢复成功',
  restoreSourceLabel: '恢复来源',
  currentlyRunningBadge: '当前运行',
  restoringVersion: '正在恢复版本',
  restoreFailedBanner: '恢复失败',
  restoreFailedHint: '当前线上版本未受影响。',
  concurrentDeployBusy: '当前有上线任务正在进行，请稍后再试。',
  codeSync: '代码同步',
  autoSync: '自动检查代码更新',
  autoSyncHint: '发现新版本后会通知你，不会自动上线。',
  saveSettings: '保存设置',
  savingSettings: '保存中…',
  settingsSaved: '已保存',
  noVersions: '还没有上线版本。',
  commitMessage: '代码说明',
  healthStatus: '健康状态',
  lastHealthCheck: '最近检查',
  responseTime: '响应速度',
  healthHistory: '最近运行情况',
  waitingHealthCheck: '等待首次检测',
  runtimeStatusCard: '运行状态',
  publicAccess: '公网访问',
  publicAccessOk: '正常',
  publicAccessFail: '异常',
  publicAccessUnknown: '待确认',
  uptime: '运行时长',
  viewRuntimeDetails: '查看运行详情',
  recentErrorTitle: '最近错误',
  noRecentError: '最近没有发现运行异常。',
  startupSummaryTitle: '最近启动',
  recommendedActionTitle: '建议',
  technicalLogs: '技术日志',
  loadMoreLogs: '加载更多',
  runtimePageTitle: '运行详情',
  statusPendingHint: '暂时无法确认运行状态',
  copyFixPrompt: '复制修复提示词',
  autoDetectBranch: '自动检测默认分支',
  keepDefaultBranch: '如果不知道代码版本，请保持默认。',
  appPurpose: '应用用途',
  appPurposeHint: '说明这个应用主要做什么，和底层技术无关。',
  serverNameHint: '用于自己识别服务器。',
  serverHostHint: '填写服务器公网IP。',
  serverPortHint: '默认22。',
  serverUsernameHint: '服务器登录账号。',
  serverPasswordHint: '不会展示。',
  uploadPreparing: '准备上传',
  uploadUploading: '上传中',
  uploadCompleted: '上传完成',
  uploadFailed: '上传失败',
  advancedRemoteLogs: '高级日志',
  sshLogs: '连接日志',
  uploadLogs: '上传日志',
  deployLogs: '部署日志',
  codePlatforms: '代码平台',
  codePlatformsHint: '连接 GitHub，授权私有仓库后即可一键上线。',
  githubConnected: '✓ GitHub 已连接',
  githubNotConnected: '未连接',
  githubNeedsReauth: '需要重新授权',
  connectGithub: '连接 GitHub',
  reconnectGithub: '重新授权',
  disconnectGithub: '断开连接',
  selectGithubRepo: '选择代码仓库',
  searchRepos: '搜索仓库',
  publicRepoMode: '使用公开仓库地址',
  githubAppMode: '连接 GitHub',
  githubAuthAccess: '已授权',
  githubRepoPrivate: '私有',
  githubRepoPublic: '公开',
  githubSelectReposHint: '建议仅选择要上线的仓库，不必授权全部仓库。',
  githubNotConfigured: '服务器尚未配置 GitHub App，请先完成环境配置。',
  githubDisconnectConfirm: '断开后不会删除已有应用，但重新上线与代码同步需要重新授权。',
  iosAppType: 'iOS APP',
  iosUnsupportedTitle: '当前版本暂不支持直接发布 iOS APP。',
  iosUnsupportedBody:
    'LaunchOS 已识别这是一个 iOS 原生应用。\n目前 Web/服务器上线能力不能用于 iOS APP。\n后续需要通过 Xcode、Apple 签名和 App Store Connect 完成发布。',
  multiTargetTitle: '发现多个可上线内容',
  multiTargetHint: '你要上线哪一部分？请先选择；当前不会自动替你决定。',
  multiTargetNotSupported: '当前暂不支持直接发布',
  multiTargetCanLaunch: '可以上线',
  multiTargetSelect: '选择上线',
  appComposition: '应用组成',
  appCompositionHint: '这个应用包含多个可独立上线的部分。',
  appCompositionNotLive: '尚未上线',
  appCompositionUnsupported: '当前暂不支持直接发布',
  appCompositionView: '查看',
  appCompositionScanning: '正在识别应用组成…',
  appCompositionEmpty: '暂时没有识别到可上线内容',
  appCompositionNoUrl: '尚未生成访问地址。',
  unitCodeUpdated: '代码有更新',
  viewDetectResult: '查看检测结果',
  multipleVisitEntries: '多个访问入口',
  uploadTimedOut: '上传应用超时。',
} as const;

export const ONBOARDING_STEPS = [
  {
    title: '连接代码',
    description: '把 GitHub 地址告诉我们，不用准备服务器。',
  },
  {
    title: '智能检测',
    description: 'LaunchOS 会自动识别应用，并准备上线方案。',
  },
  {
    title: '一键上线',
    description: '选择 LaunchOS 自动托管或你的服务器，确认后即可发布。',
  },
] as const;
